# Generated by Django 5.1.7 on 2025-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0003_remove_order_items_alter_order_status_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="buyer.cartitem"),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
