# Generated by Django 5.1.7 on 2025-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0004_order_items_delete_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="farmer_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="farmer_lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
