# Generated by Django 5.1.7 on 2025-06-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0007_order_paypal_order_id_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paypal_order_id",
        ),
    ]
