# Generated by Django 5.1.7 on 2025-06-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_produce_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="produce",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
