# Generated by Django 5.1.7 on 2025-06-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_produce_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farmer",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
