# Generated by Django 5.1.7 on 2025-06-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0006_buyer_latitude_buyer_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paypal_order_id",
            field=models.CharField(
                blank=True,
                help_text="PayPal Order ID for tracking",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PICKED_UP", "Picked Up"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
