# Generated by Django 5.1.7 on 2025-06-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_logistics",
            field=models.BooleanField(default=False),
        ),
    ]
