# Generated by Django 5.1.7 on 2025-06-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0005_order_buyer_lat_order_buyer_lon_order_farmer_lat_and_more"),
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.FloatField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.logisticspartner",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="buyer.order"
                    ),
                ),
            ],
        ),
    ]
