# Generated by Django 5.1.7 on 2025-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produce",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fruits", "Fruits"),
                    ("Vegetables", "Vegetables"),
                    ("Grains", "Grains"),
                    ("Dairy", "Dairy"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=20,
            ),
        ),
    ]
